add_newline = true

format = "$all"

[character]
success_symbol = "[](bold green)"
error_symbol = "[](bold red)"

[directory]
truncation_length = 8
truncate_to_repo = true
format = "[$path]($style)[$read_only]($read_only_style) "
style = "bold cyan"
truncation_symbol = "…/"
