#!/bin/sh
song=$(playerctl metadata --player=spotify --format "Title: {{ xesam:title }}\nArtist: {{ xesam:artist }}\nAlbum: {{ xesam:album }}")
notify-send "Music Player" "$song" --icon=/usr/share/icons/Papirus/64x64/apps/spotify.svg
